import "./globals.css";
// import { Inter  } from "next/font/google";
import Header from "../components/header";
import Noise from "./grainEff";
// const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Krish.dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        < Header />
        {children}
        <Noise></Noise>
      </body>
    </html>
  );
}
