import "./globals.css";
import { Inter  } from "next/font/google";
import Header from "../components/header";
import Noise from "./grainEff";
// import CustomCursor from "@/components/cursor";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        {/* <CustomCursor></CustomCursor> */}
      </body>
    </html>
  );
}
